---
nameSpaces:
  - name: name-space-1
    topics:
      - name: tp-a
        subscriptions:
          - name: sub-1
          - name: sub-2
        queues:
          - name: queue-1
          - name: queue-1
      - name: tp-b
        subscriptions:
          - name: sub-1
          - name: sub-2
        queues:
          - name: queue-1
          - name: queue-1

  - name: name-space-2
    topics:
      - name: tp-c
        subscriptions:
          - name: sub-1
          - name: sub-2
        queues:
          - name: queue-1
          - name: queue-1
      - name: tp-d
        subscriptions:
          - name: sub-1
          - name: sub-2
        queues:
          - name: queue-1
          - name: queue-1
